### ISSUE TITLE
Use the /opt/virtualenv/bluse3.9/ environment

### ISSUE THREAD

**Issue by lacker** [UCBerkeleySETI/commensal-automator#6]
3.5 is end-of-lifed, some libraries don't support it any more. The target selector is already using the 3.9 environment so this would also make the overall situation simpler.

**Comment by danielczech** [comment]
I've moved it to the 3.9 environment. All seems to be well so far, but will wait and see before closing.

**Comment by lacker** [comment]
Looks good now
